---
- name: Check package is installed
  hosts: web
  tasks:

  - name: "Check if figlet is installed"
    package_facts:
     manager: "auto"

  - name: "Python test result"
    debug:
      msg: "PYTHON 39 found"
    when: "'python39' in ansible_facts.packages"

  - name: "Python 39 test result"
    fail:
      msg: "PYTHON 39 NOT found"
    when: "'python39' not in ansible_facts.packages"
