---
- name: Install figlet
  hosts: web
  become: yes
  tasks:
          - name: Install packages
            yum:
             name:
               - figlet
             state: present
             
          - name: Install commuinty ansible modules
            shell: ansible-galaxy collection install community.general
            args:
              executable: /bin/bash

