---
- name: Telegram notifaction
  hosts: localhost
  become: yes
  tasks:
   - name: Install commuinty ansible modules
     shell: ansible-galaxy collection install community.general
     args:
      executable: /bin/bash

   - name: Send notify to Telegram
     community.general.telegram:
      token: '2119002571:AAE306nVA-Rq0QapKUwb5I2_LmEoxMY5wRY'
      api_args:
        chat_id: -545438160
        parse_mode: "markdown"
        text: "Group X has completed the ansible tasks."
        disable_web_page_preview: True
        disable_notification: True
